#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = Path(os.environ.get("BMO_RUNTIME_ENV_FILE", str(Path.home() / ".config" / "bmo-runtime.env")))
DEFAULT_OUTPUT = ROOT / "workflows" / "bmo-runtime-profile-v2.json"

PROFILES = {
    "dev": {
        "BMO_TEXT_MODEL": "nemotron-mini:4b-instruct-q2_K",
        "BMO_LOCAL_TEXT_MODEL": "nemotron-mini:4b-instruct-q2_K",
        "BMO_CLOUD_TEXT_MODEL": "nemotron-3-super",
        "BMO_CLOUD_TEXT_ENDPOINT": "",
        "BMO_CLOUD_API_STYLE": "openai",
        "BMO_CLOUD_API_KEY": "",
        "BMO_VISION_MODEL": "moondream",
        "BMO_TTS_MODE": "auto",
        "BMO_STT_BACKEND": "typed",
        "BMO_STT_COMMAND": "",
        "BMO_WAKE_WORD": "off",
        "BMO_WAKE_WORD_PHRASE": "hey bmo",
        "BMO_FACE_RENDERER": "basic",
        "BMO_MODEL_ROUTE_DEFAULT": "local",
        "BMO_OLLAMA_TIMEOUT_SEC": "45",
        "BMO_MAX_RESPONSE_SENTENCES": "4",
        "BMO_SYSTEM_PROMPT_EXTRAS": "Keep responses concise, practical, and BMO-like.",
    },
    "snappy": {
        "BMO_TEXT_MODEL": "nemotron-mini:4b-instruct-q2_K",
        "BMO_LOCAL_TEXT_MODEL": "nemotron-mini:4b-instruct-q2_K",
        "BMO_CLOUD_TEXT_MODEL": "nemotron-3-super",
        "BMO_CLOUD_TEXT_ENDPOINT": "",
        "BMO_CLOUD_API_STYLE": "openai",
        "BMO_CLOUD_API_KEY": "",
        "BMO_VISION_MODEL": "moondream",
        "BMO_TTS_MODE": "auto",
        "BMO_STT_BACKEND": "typed",
        "BMO_STT_COMMAND": "",
        "BMO_WAKE_WORD": "off",
        "BMO_WAKE_WORD_PHRASE": "hey bmo",
        "BMO_FACE_RENDERER": "basic",
        "BMO_MODEL_ROUTE_DEFAULT": "local",
        "BMO_OLLAMA_TIMEOUT_SEC": "25",
        "BMO_MAX_RESPONSE_SENTENCES": "2",
        "BMO_SYSTEM_PROMPT_EXTRAS": "Prioritize fast, short answers.",
    },
    "robust": {
        "BMO_TEXT_MODEL": "nemotron-mini:4b-instruct-q4_K_M",
        "BMO_LOCAL_TEXT_MODEL": "nemotron-mini:4b-instruct-q4_K_M",
        "BMO_CLOUD_TEXT_MODEL": "nemotron-3-super",
        "BMO_CLOUD_TEXT_ENDPOINT": "",
        "BMO_CLOUD_API_STYLE": "openai",
        "BMO_CLOUD_API_KEY": "",
        "BMO_VISION_MODEL": "moondream",
        "BMO_TTS_MODE": "auto",
        "BMO_STT_BACKEND": "typed",
        "BMO_STT_COMMAND": "",
        "BMO_WAKE_WORD": "off",
        "BMO_WAKE_WORD_PHRASE": "hey bmo",
        "BMO_FACE_RENDERER": "rich",
        "BMO_MODEL_ROUTE_DEFAULT": "local",
        "BMO_OLLAMA_TIMEOUT_SEC": "90",
        "BMO_MAX_RESPONSE_SENTENCES": "5",
        "BMO_SYSTEM_PROMPT_EXTRAS": "Take a little more time for accuracy, but stay clear and concise.",
    },
}


def save_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by scripts/apply-bmo-runtime-profile-v2.py", ""]
    for key, value in values.items():
        lines.append(f"{key}={shlex.quote(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Apply a BMO runtime slice 2 profile.")
    parser.add_argument("profile", choices=sorted(PROFILES))
    parser.add_argument("--env-file", default=str(ENV_FILE))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    values = dict(PROFILES[args.profile])
    env_path = Path(args.env_file).expanduser()
    save_env(env_path, values)

    output = Path(args.output)
    if not output.is_absolute():
        output = ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "profile": args.profile,
        "env_file": str(env_path),
        "values": values,
    }
    output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
