#!/usr/bin/env bash
set -euo pipefail

BASE_BRANCH="${BASE_BRANCH:-master}"
BRANCH_NAME="${BRANCH_NAME:-automation/fork-governor-sync}"
DONORS_PATH="${DONORS_PATH:-DONORS.yaml}"

if [ -z "${GH_TOKEN:-}" ]; then
  echo "Missing GH_TOKEN for PR helper." >&2
  exit 1
fi

git config user.name "fork-governor[bot]"
git config user.email "fork-governor[bot]@users.noreply.github.com"
git checkout -B "$BRANCH_NAME"
git add "$DONORS_PATH"

if git diff --cached --quiet; then
  echo "No staged DONORS changes."
  exit 0
fi

git commit -m "chore(donors): refresh fork inventory"
git push --force origin "$BRANCH_NAME"

BODY_FILE="$(mktemp)"
cat > "$BODY_FILE" <<'EOF'
## Summary
- refresh `DONORS.yaml` from live fork inventory
- bootstrap the upstream sync workflow into newly discovered forks
- surface repo-level blockers through generated donor status fields

## Notes
This PR is generated by the fork governor workflow.
If a fork is locked or needs manual resolution, that status will appear in `DONORS.yaml`.
EOF

PR_NUMBER="$(gh pr list --state open --head "$BRANCH_NAME" --json number --jq '.[0].number // empty')"
if [ -n "$PR_NUMBER" ]; then
  gh pr edit "$PR_NUMBER" --title "chore(donors): refresh fork inventory" --body-file "$BODY_FILE"
else
  gh pr create --base "$BASE_BRANCH" --head "$BRANCH_NAME" --title "chore(donors): refresh fork inventory" --body-file "$BODY_FILE"
fi
