param(
  [string]$RepoDir = "$env:USERPROFILE\.bmo-stack",
  [string]$OpenClawPrefix = "$env:USERPROFILE\.openclaw"
)

$ErrorActionPreference = 'Stop'

$RepoUrl = 'https://github.com/codysumpter-cloud/bmo-stack.git'
$ArchiveUrl = 'https://github.com/codysumpter-cloud/bmo-stack/archive/refs/heads/master.zip'

function Say($Message) {
  Write-Host ""
  Write-Host "== $Message =="
}

function Have-Cmd($Name) {
  return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ensure-Repo {
  Say 'Preparing bmo-stack repo'
  if (Have-Cmd 'git') {
    if (Test-Path "$RepoDir\.git") {
      git -C $RepoDir pull --ff-only | Out-Null
    } else {
      New-Item -ItemType Directory -Path (Split-Path $RepoDir -Parent) -Force | Out-Null
      git clone $RepoUrl $RepoDir
    }
  } else {
    $tmp = Join-Path $env:TEMP ("bmo-stack-" + [guid]::NewGuid().ToString())
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    $zipPath = Join-Path $tmp 'bmo-stack.zip'
    Invoke-WebRequest -Uri $ArchiveUrl -OutFile $zipPath
    Expand-Archive -Path $zipPath -DestinationPath $tmp -Force
    if (Test-Path $RepoDir) { Remove-Item -Recurse -Force $RepoDir }
    Move-Item (Join-Path $tmp 'bmo-stack-master') $RepoDir
  }
}

function Write-LocalModelAutoEnv {
  Say 'Selecting local model profile'
  $outFile = Join-Path $RepoDir 'config\local-model.auto.env'
  New-Item -ItemType Directory -Path (Split-Path $outFile -Parent) -Force | Out-Null

  $platform = 'windows'
  $arch = $env:PROCESSOR_ARCHITECTURE
  $ramBytes = (Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory
  $ramGb = [math]::Floor($ramBytes / 1GB)

  $vramMb = 0
  try {
    $gpuLines = & nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>$null
    if ($gpuLines) {
      $first = ($gpuLines | Select-Object -First 1).ToString().Trim()
      if ($first) { $vramMb = [int]$first }
    }
  } catch {
    $vramMb = 0
  }
  $vramGb = [math]::Floor($vramMb / 1024)

  $profile = 'nemotron3-nano-4b-q4km-cpu-safe'
  $modelId = 'nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF'
  $modelFamily = 'Nemotron 3 Nano 4B'
  $quant = 'Q4_K_M'
  $runtime = 'llama.cpp'
  $mode = 'cpu'
  $reason = 'safe default for low-memory or non-NVIDIA hosts'
  $cloudFallback = 'true'

  if ($vramGb -ge 16) {
    $profile = 'nemotron3-nano-30b-a3b-q3kl-hybrid'
    $modelId = 'nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16'
    $modelFamily = 'Nemotron 3 Nano 30B-A3B'
    $quant = 'Q3_K_L'
    $runtime = 'llama.cpp'
    $mode = 'hybrid'
    $reason = 'NVIDIA GPU with enough VRAM for a practical 30B hybrid profile'
  } elseif ($vramGb -ge 12) {
    $profile = 'nemotron3-nano-4b-q4km-gpu'
    $modelId = 'nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF'
    $modelFamily = 'Nemotron 3 Nano 4B'
    $quant = 'Q4_K_M'
    $runtime = 'llama.cpp'
    $mode = 'gpu'
    $reason = 'NVIDIA GPU detected but not enough VRAM for the heavier 30B profile'
  }

  @(
    '# Auto-generated by scripts/install-oneclick.ps1'
    "BMO_LOCAL_MODEL_PROFILE=$profile"
    "BMO_LOCAL_MODEL_ID=$modelId"
    "BMO_LOCAL_MODEL_FAMILY=$modelFamily"
    "BMO_LOCAL_MODEL_QUANT=$quant"
    "BMO_LOCAL_MODEL_RUNTIME=$runtime"
    "BMO_LOCAL_MODEL_MODE=$mode"
    "BMO_LOCAL_MODEL_PLATFORM=$platform"
    "BMO_LOCAL_MODEL_ARCH=$arch"
    "BMO_LOCAL_MODEL_RAM_GB=$ramGb"
    "BMO_LOCAL_MODEL_VRAM_GB=$vramGb"
    "BMO_LOCAL_MODEL_REASON=$reason"
    "BMO_LOCAL_MODEL_CLOUD_FALLBACK=$cloudFallback"
  ) | Set-Content -Path $outFile -Encoding UTF8

  Copy-Item $outFile (Join-Path $RepoDir 'config\local-model.selected.env') -Force
  Get-Content $outFile
}

function Ensure-EnvFiles {
  Say 'Writing env files'
  $envFile = Join-Path $RepoDir '.env'
  $envExample = Join-Path $RepoDir '.env.example'
  if ((-not (Test-Path $envFile)) -and (Test-Path $envExample)) {
    Copy-Item $envExample $envFile
  }
}

function Ensure-OpenClawCli {
  Say 'Ensuring OpenClaw CLI'
  $existing = Have-Cmd 'openclaw.cmd'
  $localCli = Join-Path $OpenClawPrefix 'bin\openclaw.cmd'
  if ($existing -or (Test-Path $localCli)) {
    Write-Host 'OpenClaw already installed.'
    return
  }
  $installScript = Join-Path $env:TEMP 'openclaw-install.ps1'
  Invoke-WebRequest -Uri 'https://openclaw.ai/install-cli.ps1' -OutFile $installScript
  powershell -ExecutionPolicy Bypass -File $installScript -Prefix $OpenClawPrefix -NoOnboard
}

function Print-Summary {
  Say 'Install complete'
  Write-Host "repo: $RepoDir"
  $profile = (Get-Content (Join-Path $RepoDir 'config\local-model.auto.env') | Where-Object { $_ -like 'BMO_LOCAL_MODEL_PROFILE=*' }) -replace '^BMO_LOCAL_MODEL_PROFILE=',''
  $family = (Get-Content (Join-Path $RepoDir 'config\local-model.auto.env') | Where-Object { $_ -like 'BMO_LOCAL_MODEL_FAMILY=*' }) -replace '^BMO_LOCAL_MODEL_FAMILY=',''
  $reason = (Get-Content (Join-Path $RepoDir 'config\local-model.auto.env') | Where-Object { $_ -like 'BMO_LOCAL_MODEL_REASON=*' }) -replace '^BMO_LOCAL_MODEL_REASON=',''
  Write-Host "model profile: $profile"
  Write-Host "model family: $family"
  Write-Host "reason: $reason"
  Write-Host ''
  Write-Host 'Next recommended checks:'
  Write-Host "  cd $RepoDir"
  Write-Host '  make doctor'
  Write-Host ''
  Write-Host 'If Docker Desktop is not installed yet, install it later for sandbox and auxiliary-service features.'
}

Ensure-Repo
Ensure-EnvFiles
Write-LocalModelAutoEnv
Ensure-OpenClawCli
Print-Summary
