param(
  [string]$SourceFile = ".\config\local-model.auto.env",
  [string]$DestFile = ".\config\runtime.auto.env"
)

$ErrorActionPreference = 'Stop'

function Read-Value($Path, $Key) {
  if (-not (Test-Path $Path)) { return $null }
  foreach ($line in Get-Content $Path) {
    if ($line -match "^$Key=(.*)$") {
      return $Matches[1].Trim('"')
    }
  }
  return $null
}

if (-not (Test-Path $SourceFile)) {
  throw "Missing local model selection file: $SourceFile"
}

$profile = Read-Value $SourceFile 'BMO_LOCAL_MODEL_PROFILE'
$modelId = Read-Value $SourceFile 'BMO_LOCAL_MODEL_ID'
$family = Read-Value $SourceFile 'BMO_LOCAL_MODEL_FAMILY'
$quant = Read-Value $SourceFile 'BMO_LOCAL_MODEL_QUANT'
$runtime = Read-Value $SourceFile 'BMO_LOCAL_MODEL_RUNTIME'
$mode = Read-Value $SourceFile 'BMO_LOCAL_MODEL_MODE'
$platform = Read-Value $SourceFile 'BMO_LOCAL_MODEL_PLATFORM'
$arch = Read-Value $SourceFile 'BMO_LOCAL_MODEL_ARCH'
$ramGb = Read-Value $SourceFile 'BMO_LOCAL_MODEL_RAM_GB'
$vramGb = Read-Value $SourceFile 'BMO_LOCAL_MODEL_VRAM_GB'
$reason = Read-Value $SourceFile 'BMO_LOCAL_MODEL_REASON'
$cloudFallback = Read-Value $SourceFile 'BMO_LOCAL_MODEL_CLOUD_FALLBACK'

$executionPolicy = 'local-with-cloud-fallback'
$primaryProvider = 'local'
if ($mode -eq 'hybrid') {
  $primaryProvider = 'local-hybrid'
}

New-Item -ItemType Directory -Path (Split-Path $DestFile -Parent) -Force | Out-Null
@(
  '# Auto-generated by scripts/render-runtime-env.ps1'
  "BMO_RUNTIME_PROFILE=\"$profile\""
  "BMO_RUNTIME_MODEL_ID=\"$modelId\""
  "BMO_RUNTIME_MODEL_FAMILY=\"$family\""
  "BMO_RUNTIME_MODEL_QUANT=\"$quant\""
  "BMO_RUNTIME_MODEL_RUNTIME=\"$runtime\""
  "BMO_RUNTIME_MODEL_MODE=\"$mode\""
  "BMO_RUNTIME_PLATFORM=\"$platform\""
  "BMO_RUNTIME_ARCH=\"$arch\""
  "BMO_RUNTIME_RAM_GB=\"$ramGb\""
  "BMO_RUNTIME_VRAM_GB=\"$vramGb\""
  "BMO_RUNTIME_REASON=\"$reason\""
  "BMO_RUNTIME_CLOUD_FALLBACK_ALLOWED=\"$cloudFallback\""
  "BMO_RUNTIME_EXECUTION_POLICY=\"$executionPolicy\""
  "BMO_RUNTIME_PRIMARY_PROVIDER=\"$primaryProvider\""
  'BMO_RUNTIME_LOCAL_ENABLED="true"'
  'OMNI_ENABLE_LOCAL=true'
  'OMNI_ROUTING_STRATEGY=local-first'
  "OMNI_LOCAL_MODEL_PROFILE=\"$profile\""
  "OMNI_LOCAL_MODEL_SOURCE=\"$modelId\""
  "OMNI_LOCAL_MODEL_RUNTIME=\"$runtime\""
  "OMNI_LOCAL_MODEL_QUANT=\"$quant\""
) | Set-Content -Path $DestFile -Encoding UTF8

Write-Host "Wrote $DestFile"
Get-Content $DestFile
