#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SRC_FILE="${1:-$ROOT_DIR/config/local-model.auto.env}"
DST_FILE="${2:-$ROOT_DIR/config/runtime.auto.env}"

read_value() {
  local key="$1"
  awk -F'=' -v k="$key" '$1 == k {sub($1 FS, "", $0); print $0}' "$SRC_FILE" | head -n1
}

if [[ ! -f "$SRC_FILE" ]]; then
  echo "Error: missing local model selection file: $SRC_FILE" >&2
  exit 1
fi

profile="$(read_value BMO_LOCAL_MODEL_PROFILE)"
model_id="$(read_value BMO_LOCAL_MODEL_ID)"
family="$(read_value BMO_LOCAL_MODEL_FAMILY)"
quant="$(read_value BMO_LOCAL_MODEL_QUANT)"
runtime="$(read_value BMO_LOCAL_MODEL_RUNTIME)"
mode="$(read_value BMO_LOCAL_MODEL_MODE)"
platform="$(read_value BMO_LOCAL_MODEL_PLATFORM)"
arch="$(read_value BMO_LOCAL_MODEL_ARCH)"
ram_gb="$(read_value BMO_LOCAL_MODEL_RAM_GB)"
vram_gb="$(read_value BMO_LOCAL_MODEL_VRAM_GB)"
reason="$(read_value BMO_LOCAL_MODEL_REASON)"
cloud_fallback="$(read_value BMO_LOCAL_MODEL_CLOUD_FALLBACK)"

execution_policy="local-with-cloud-fallback"
primary_provider="local"
if [[ "$mode" == "hybrid" ]]; then
  primary_provider="local-hybrid"
fi

mkdir -p "$(dirname "$DST_FILE")"
cat > "$DST_FILE" <<EOF
# Auto-generated by scripts/render-runtime-env.sh
BMO_RUNTIME_PROFILE="$profile"
BMO_RUNTIME_MODEL_ID="$model_id"
BMO_RUNTIME_MODEL_FAMILY="$family"
BMO_RUNTIME_MODEL_QUANT="$quant"
BMO_RUNTIME_MODEL_RUNTIME="$runtime"
BMO_RUNTIME_MODEL_MODE="$mode"
BMO_RUNTIME_PLATFORM="$platform"
BMO_RUNTIME_ARCH="$arch"
BMO_RUNTIME_RAM_GB="$ram_gb"
BMO_RUNTIME_VRAM_GB="$vram_gb"
BMO_RUNTIME_REASON="$reason"
BMO_RUNTIME_CLOUD_FALLBACK_ALLOWED="$cloud_fallback"
BMO_RUNTIME_EXECUTION_POLICY="$execution_policy"
BMO_RUNTIME_PRIMARY_PROVIDER="$primary_provider"
BMO_RUNTIME_LOCAL_ENABLED="true"
OMNI_ENABLE_LOCAL=true
OMNI_ROUTING_STRATEGY=local-first
OMNI_LOCAL_MODEL_PROFILE="$profile"
OMNI_LOCAL_MODEL_SOURCE="$model_id"
OMNI_LOCAL_MODEL_RUNTIME="$runtime"
OMNI_LOCAL_MODEL_QUANT="$quant"
EOF

echo "Wrote $DST_FILE"
cat "$DST_FILE"
